// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const nodeEnv = process.env.NODE_ENV || "local";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: `prisma/${nodeEnv}/migrations`,
    seed: "tsx prisma/seeds/index.ts"
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
